# Generated by Django 3.2.6 on 2021-08-26 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_categ_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categ',
            options={'ordering': ('name',), 'verbose_name': 'categories', 'verbose_name_plural': 'categories'},
        ),
    ]
